worker_processes 1;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    sendfile on;

    server {
        listen 80;
        server_name balloos.in.ua;

        location / {
            proxy_pass http://balloons_frontend_1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://balloons_backend_1:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
