worker_processes 1;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    sendfile on;

    # Фронтенд (balloos.in.ua)
    server {
        listen 80;
        server_name balloos.in.ua www.balloos.in.ua;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }

    # Бекенд (api.balloos.in.ua)
    server {
        listen 80;
        server_name api.balloos.in.ua;

        location / {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
# worker_processes 1;
# events { worker_connections 1024; }
# http {
#     include /etc/nginx/mime.types;
#     sendfile on;

#     server {
#         listen 80;
#         server_name balloos.in.ua www.balloos.in.ua;

#         location / {
#             root /usr/share/nginx/html;
#             index index.html index.htm;
#             try_files $uri $uri/ /index.html;
#         }

#         location /api/ {
#             proxy_pass http://balloons_backend_1:5000/;  # Зміни на 5000
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#             proxy_connect_timeout 10s;
#             proxy_read_timeout 10s;
#         }

#         error_page 500 502 503 504 /50x.html;
#         location = /50x.html {
#             root /usr/share/nginx/html;
#         }
#     }
# }